name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python 3.8 and virtualenv
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: |
          sudo apt update
          sudo apt install python3-pip
          python -m pip install virtualenv

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check Python environment
        run: ./gradlew checkPython

      - name: Run tests
        run: ./gradlew test


  code-style:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check code style
        run: ./gradlew ktlintCheck

